services:
  - type: web
    name: api-productos-sepa
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app.api:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: API_KEY
        sync: false
      - key: DB_HOST
        fromDatabase:
          name: productos-sepa-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: productos-sepa-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: productos-sepa-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: productos-sepa-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: productos-sepa-db
          property: password

  - type: cron
    name: actualizar-datos-sepa
    env: python
    schedule: "10 13 * * *"
    buildCommand: pip install -r requirements.txt
    startCommand: python scripts/descargar_e_importar.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DB_HOST
        fromDatabase:
          name: productos-sepa-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: productos-sepa-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: productos-sepa-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: productos-sepa-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: productos-sepa-db
          property: password

databases:
  - name: productos-sepa-db

